name: Workflow test

on: 
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: test
      run: |
        pytest test/unittest.py